name: Go

on:
  workflow_dispatch:

env:
  GITHUB_NAME: Abirdcfly
  GITHUB_EMAIL: fp544037857@gmail.com
  WITH_REPOS: false
  WITH_STARED: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My GitHub Status
        uses: ./
